#!/bin/bash
###############################################################################
# Parking Empty Alert — Setup Script
# Run:  bash setup.sh
###############################################################################
set -euo pipefail

cd "$(dirname "$0")/.."
PROJ=$(pwd)

# ─────────────────────────────────────────────────────────────
# 1. Check Docker
# ─────────────────────────────────────────────────────────────
if ! command -v docker &>/dev/null; then
  echo "❌ Docker not installed. Install: https://docs.docker.com/get-docker/"
  exit 1
fi
if ! docker compose version &>/dev/null && ! docker-compose version &>/dev/null; then
  echo "❌ Docker Compose not available. Update Docker."
  exit 1
fi
echo "✓ Docker OK"

# ─────────────────────────────────────────────────────────────
# 2. .env file
# ─────────────────────────────────────────────────────────────
if [ ! -f .env ]; then
  echo
  echo "════════════════════════════════════════════════════"
  echo "  STEP 1: Camera configuration"
  echo "════════════════════════════════════════════════════"
  read -r -p "Reolink camera IP (e.g., 192.168.1.100): " CAMERA_IP
  read -r -p "Reolink username (create a new 'frigate' user in Reolink UI with Viewer permission): " RTSP_USER
  read -r -s -p "Password for this account: " RTSP_PASSWORD; echo
  echo
  MQTT_PASSWORD=$(openssl rand -base64 24 2>/dev/null | tr -d '/+=' | head -c 20 || cat /dev/urandom | tr -dc 'a-zA-Z0-9' | head -c 20)

  echo
  echo "════════════════════════════════════════════════════"
  echo "  STEP 1B: Timezone"
  echo "════════════════════════════════════════════════════"
  DEFAULT_TZ=$(cat /etc/timezone 2>/dev/null || echo "UTC")
  read -r -p "Timezone (IANA format, e.g. Europe/Warsaw, America/New_York) [$DEFAULT_TZ]: " TZ
  TZ=${TZ:-$DEFAULT_TZ}

  echo
  echo "════════════════════════════════════════════════════"
  echo "  STEP 1C: Docker host LAN IP (for HA iframe URLs)"
  echo "════════════════════════════════════════════════════"
  # Try to auto-detect primary LAN IP
  DETECTED_IP=$(hostname -I 2>/dev/null | awk '{print $1}' || ip route get 1.1.1.1 2>/dev/null | awk '/src/ {print $7}')
  read -r -p "Docker host LAN IP (browser-accessible) [$DETECTED_IP]: " DOCKER_HOST_IP
  DOCKER_HOST_IP=${DOCKER_HOST_IP:-$DETECTED_IP}

  echo
  echo "════════════════════════════════════════════════════"
  echo "  STEP 2: WhatsApp (CallMeBot — free)"
  echo "════════════════════════════════════════════════════"
  echo "If you do NOT have a CallMeBot APIKEY yet:"
  echo "  1. Add +34 644 11 11 11 to phone contacts (as 'CallMeBot')"
  echo "  2. Open WhatsApp and send to this contact:"
  echo "     I allow callmebot to send me messages"
  echo "  3. Wait ~1 min for the reply — it will contain the APIKEY (7 digits)"
  echo
  read -r -p "Phone number (with country code, NO +; e.g., 48501234567): " WHATSAPP_PHONE
  read -r -p "CallMeBot APIKEY (7 digits): " WHATSAPP_APIKEY

  cat > .env <<EOF
CAMERA_IP=$CAMERA_IP
RTSP_USER=$RTSP_USER
RTSP_PASSWORD=$RTSP_PASSWORD
MQTT_USER=frigate
MQTT_PASSWORD=$MQTT_PASSWORD
WHATSAPP_PHONE=$WHATSAPP_PHONE
WHATSAPP_APIKEY=$WHATSAPP_APIKEY
TZ=$TZ
EOF
  chmod 600 .env
  echo "✓ .env created"

  # Update HA secrets.yaml
  cat > config/homeassistant/secrets.yaml <<EOF
# Auto-generated by setup.sh — edit only via setup.sh or manually
mqtt_user: frigate
mqtt_password: $MQTT_PASSWORD
whatsapp_phone: "$WHATSAPP_PHONE"
whatsapp_apikey: "$WHATSAPP_APIKEY"
EOF
  chmod 600 config/homeassistant/secrets.yaml

  # Substitute CAMERA_IP in frigate.yml
  sed -i.bak "s/CAMERA_IP_PLACEHOLDER/$CAMERA_IP/g" config/frigate.yml
  rm -f config/frigate.yml.bak

  # Substitute DOCKER_HOST_IP in HA Lovelace dashboard
  sed -i.bak "s/DOCKER_HOST_IP/$DOCKER_HOST_IP/g" config/homeassistant/ui-lovelace.yaml
  rm -f config/homeassistant/ui-lovelace.yaml.bak
else
  echo "✓ .env already exists (skipping prompts — delete .env to start over)"
fi

source .env

# ─────────────────────────────────────────────────────────────
# 3. Mosquitto password file
# ─────────────────────────────────────────────────────────────
echo
echo "════════════════════════════════════════════════════"
echo "  STEP 3: Generate MQTT password"
echo "════════════════════════════════════════════════════"
docker run --rm -v "$PROJ/config:/mosquitto/config" eclipse-mosquitto:2.0 \
  mosquitto_passwd -c -b /mosquitto/config/passwd "$MQTT_USER" "$MQTT_PASSWORD"
echo "✓ MQTT passwd OK"

# ─────────────────────────────────────────────────────────────
# 4. Test RTSP stream
# ─────────────────────────────────────────────────────────────
echo
echo "════════════════════════════════════════════════════"
echo "  STEP 4: Test RTSP to camera"
echo "════════════════════════════════════════════════════"
RTSP_URL="rtsp://$RTSP_USER:$RTSP_PASSWORD@$CAMERA_IP:554/h264Preview_01_sub"
echo "Test URL: rtsp://$RTSP_USER:***@$CAMERA_IP:554/h264Preview_01_sub"
if docker run --rm linuxserver/ffmpeg:latest \
    -rtsp_transport tcp -i "$RTSP_URL" \
    -frames:v 1 -f null - 2>&1 | grep -q "Stream #"; then
  echo "✓ RTSP works"
else
  echo "⚠ RTSP did not respond on h264Preview_01_sub"
  echo "   Try alternative paths — check config/frigate.yml comments"
  echo "   (h265Preview_01_sub for HEVC, or Preview_01_main for older models)"
fi

# ─────────────────────────────────────────────────────────────
# 5. WhatsApp smoke test
# ─────────────────────────────────────────────────────────────
echo
echo "════════════════════════════════════════════════════"
echo "  STEP 5: WhatsApp test"
echo "════════════════════════════════════════════════════"
TEST_MSG="parking-pack setup test — if you see this message, alerts work!"
WA_RESP=$(curl -sk --max-time 30 -G \
  --data-urlencode "phone=$WHATSAPP_PHONE" \
  --data-urlencode "text=$TEST_MSG" \
  --data-urlencode "apikey=$WHATSAPP_APIKEY" \
  "https://api.callmebot.com/whatsapp.php")
if echo "$WA_RESP" | grep -qiE "message queued|sent"; then
  echo "✓ WhatsApp test sent — check phone"
else
  echo "⚠ WhatsApp may not work — CallMeBot response:"
  echo "$WA_RESP" | head -c 500
fi

# ─────────────────────────────────────────────────────────────
# 6. Start stack
# ─────────────────────────────────────────────────────────────
echo
echo "════════════════════════════════════════════════════"
echo "  STEP 6: Start Docker stack"
echo "════════════════════════════════════════════════════"
docker compose up -d

echo
echo "════════════════════════════════════════════════════"
echo "✅ DONE!"
echo "════════════════════════════════════════════════════"
echo
echo "  Frigate UI:        http://localhost:5000"
echo "  Home Assistant:    http://localhost:8123"
echo
echo "  Next steps — see README.md (section 'Step 4 — Draw the zone')"
